== Security

At Aston Barclay we take your right to privacy seriously and we are committed to ensuring that your personal information is handled correctly and is always protected.
To protect you data our API use hypertext transfer protocol secure(HTTPS) and JWT Token.

=== Aston Barclay account

Before you can integrate Aston Barclay API, you must set up an account. Please contact Aston Barclay account manager to receive username and password.

=== JWT Token authentication

*We need to recognize you*. When you call any endpoint to get or post data to Aston Barclay API you need to add bearer authentication token.
Each request should contain `Authorization header`

====== Example
----
GET /v.1/account HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Accept: */*
Content-Type: application/json // <1>
Origin: http://localhost:9999
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ... // <2>
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
Referer: http://localhost:9999/swagger-ui.html
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,pl;q=0.8
----
<1> You need to define `application/json` content type
<2> `Authorization header` contain bearer token. More how to generate token in Chapter 3.<<_1_security_resource, Security>>

CAUTION: Bearer token is valid maximum *24 hours*. After this time you need to create new token. *Please make sure your application cover this scenario*.